#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fftw
Version  : 3.3.4
Release  : 1
URL      : http://www.fftw.org/fftw-3.3.4.tar.gz
Source0  : http://www.fftw.org/fftw-3.3.4.tar.gz
Summary  : fast Fourier transform library
Group    : Development/Tools
License  : GPL-2.0
Requires: fftw-bin
Requires: fftw-doc

%description
FFTW is a free collection of fast C routines for computing the
Discrete Fourier Transform in one or more dimensions.  It includes
complex, real, symmetric, and parallel transforms, and can handle
arbitrary array sizes efficiently.  FFTW is typically faster than
other publically-available FFT implementations, and is even
competitive with vendor-tuned libraries.  (See our web page
http://fftw.org/ for extensive benchmarks.)  To achieve this
performance, FFTW uses novel code-generation and runtime
self-optimization techniques (along with many other tricks).

%package bin
Summary: bin components for the fftw package.
Group: Binaries

%description bin
bin components for the fftw package.


%package dev
Summary: dev components for the fftw package.
Group: Development
Requires: fftw-bin
Provides: fftw-devel

%description dev
dev components for the fftw package.


%package doc
Summary: doc components for the fftw package.
Group: Documentation

%description doc
doc components for the fftw package.


%prep
%setup -q -n fftw-3.3.4

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fftw-wisdom
/usr/bin/fftw-wisdom-to-conf

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/fftw3.f
/usr/include/fftw3.f03
/usr/include/fftw3l.f03
/usr/include/fftw3q.f03
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
